import NavBar from "@/components/navBar";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <div className="flex justify-center">
          <button className="bg-[#252432] mt-[65px] text-[#FFFFFF] px-[58px] py-[18px] rounded-[10px]">
            Get in Touch
          </button>
        </div>
      </body>
    </html>
  );
}
